export const fish_list = [
    "Anchovy",
    "Bass (black)",
    "Bass (striped)",
    "Bluefish",
    "Buffalo Fish",
    "Butterfish",
    "Calamari (Squid)",
    "Carp",
    "Catfish (farm-raised)",
    "Chilean sea bass",
    "Clam",
    "Cod",
    "Crab (Blue, King and Snow)",
    "Crayfish (Crawfish)",
    "Croaker (Atlantic)",
    "Flounder",
    "Golden Snapper",
    "Grouper",
    "Haddock",
    "Hake",
    "Halibut",
    "Herring",
    "Jack (Amber, Crevalle)",
    "Jacksmelt",
    "King Mackerel",
    "Lobster (northern, Maine, American)",
    "Lobster (spiny)",
    "Mackerel (Atlantic, jack, chub)",
    "Mahi Mahi (Dolphin-fish)",
    "Marlin",
    "Mullet",
    "Orange Roughy",
    "Oysters (cooked)",
    "Perch (Freshwater)",
    "Perch (Ocean)",
    "Pickerel",
    "Plaice",
    "Pollock",
    "Pompano (Florida)",
    "Rainbow Trout (farm-raised)",
    "Sablefish",
    "Salmon (wild or farm-raised)",
    "Sardine",
    "Scallop",
    "Scorpion Fish",
    "Sea Trout",
    "Shad (American)",
    "Shark",
    "Shrimp",
    "Snapper",
    "Sole",
    "Spanish Mackerel (Gulf of Mexico)",
    "Spanish Mackerel (South Atlantic)",
    "Squid (Calamari)",
    "Swordfish",
    "Tilapia",
    "Tilefish (Atlantic)",
    "Tilefish (Gulf of Mexico)",
    "Tuna",
    "Walleye (Great Lakes, Canada)",
    "Weakfish",
    "White Croaker (Pacific)",
    "Whitefish",
    "Whiting",
  ];

const animals = [
    "🐟",
    "🐠",
    "🐡",
    "🦑",
    "🦐",
    "🐙",
    "🦀",
    "🐢",
    "🐳",
    "🐬",
    "🐋",
    "🦈",
    "🐊",
    "🐅",
    "🐆",
    "🦓",
    "🐘",
    "🦒",
    "🐫",
    "🦏",
    "🦛",
    "🐪",
    "🐃",
    "🐄",
    "🐎",
    "🐖",
    "🐏",
    "🐑",
    "🦙",
    "🐐",
    "🦌",
    "🐕",
    "🦮",
    "🐕‍🦺",
    "🦩",
    "🦢",
    "🕊️",
    "🦆",
    "🦉",
    "🦜",
    "🐓",
    "🦃",
    "🦢",
    "🦩",
    "🦜",
    "🐇",
  ];